# Generated by Django 4.0 on 2021-12-09 05:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_psec', '0003_rename_descricao_questao_descricao_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_apoio',
            name='descricao_seo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material_apoio',
            name='titulo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
