# Generated by Django 4.0 on 2021-12-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_psec', '0004_material_apoio_descricao_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_apoio',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_psec.disciplina'),
            preserve_default=False,
        ),
    ]
