# Generated by Django 4.0 on 2021-12-09 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_psec', '0005_material_apoio_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_apoio',
            name='resumo',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
