# Generated by Django 4.0 on 2021-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_psec', '0006_material_apoio_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='show',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
